project:
  type: website
  output-dir: docs

website:
  #favicon: "images/linkedinpic.jpg"
  title: "Enoque Filho"
  navbar:
    background: primary
    #foreground: secondary
    left:
      - icon: house
        href: index.qmd
        text: Sobre mim
      - icon: bar-chart-line
        href: projetos.qmd
      - icon: pen
        href: blog.qmd
        text: Blog
    right:
      - icon: github
        href: "https://github.com/enoque-filho"
        aria-label: GitHub
      - icon: linkedin
        href: "https://linkedin.com/in/enoque-filho-70200b183"
        aria-label: LinkedIn
  page-footer:
    background: primary
    center: 
      - text: | # how to make markdown links works here?
           Criado com Posit <a href="https://quarto.org/">Quarto</a>

format: 
  html:
    #css: styles.css
    theme:
      light: flatly
      dark: darkly
    highlight-style: nord
    toc: true
    toc-title: 'Nesta pagina'
    author:
      - name: "Enoque S. Anunciação Filho"
      - email: "enoquefilhomail@gmail.com"


  
editor: visual